spring:
  application:
    name: ARES
  profiles:
    active: prod

server:
  port: 9090
  servletPath: /ARES/
  
mail:
  error:
    to: nicole.sandberg@retriever.se

retriever:
  security:
    enabled: true
    md5login: true
    emaillogin: false
    iplogin: false

elasticsearch:
  port: 9350
  url: es-biz.retriever.no
  timeout: 30_000
  cluster:
    name: business
logging:
    debug: true

